name: 스포츠 뉴스 통합 모니터링

on:
  schedule:
    # 평일 모니터링 (월-금, 1-5) - 하루 8번
    - cron: '0 15 * * 1-5'    # 00:00 KST (월-금)
    - cron: '0 0 * * 1-5'     # 09:00 KST (월-금)
    - cron: '0 4 * * 1-5'     # 13:00 KST (월-금)
    - cron: '0 6 * * 1-5'     # 15:00 KST (월-금)
    - cron: '0 8 * * 1-5'     # 17:00 KST (월-금)
    - cron: '0 10 * * 1-5'    # 19:00 KST (월-금)
    - cron: '0 11 * * 1-5'    # 20:00 KST (월-금)
    - cron: '30 13 * * 1-5'   # 22:30 KST (월-금)
    
    # 일요일 모니터링 (0) - 하루 4번
    - cron: '0 2 * * 0'       # 11:00 KST (일요일)
    - cron: '0 6 * * 0'       # 15:00 KST (일요일)
    - cron: '0 10 * * 0'      # 19:00 KST (일요일)
    - cron: '0 11 * * 0'      # 20:00 KST (일요일)
  
  # 수동 실행도 가능하게
  workflow_dispatch:

jobs:
  # 기존 연합뉴스 모니터링
  yonhap-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 의존성 설치
      run: |
        pip install requests beautifulsoup4
    
    - name: 연합뉴스 스포츠 모니터링 실행
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GIST_ACCESS_TOKEN: ${{ secrets.GIST_ACCESS_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        python monitor_single.py
    
    - name: 연합뉴스 실행 결과 저장
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: yonhap-monitoring-logs
        path: "new_articles_*.txt"
        retention-days: 7

  # 새로운 네이버 스포츠 모니터링
  naver-sports-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: 코드 체크아웃
      uses: actions/checkout@v4
    
    - name: Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 의존성 설치
      run: |
        pip install requests beautifulsoup4
    
    - name: 네이버 스포츠 단독 뉴스 모니터링 실행
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GIST_ACCESS_TOKEN: ${{ secrets.GIST_ACCESS_TOKEN }}
        GIST_ID: ${{ secrets.GIST_ID }}
      run: |
        python naver_sports_monitor.py
    
    - name: 네이버 스포츠 실행 결과 저장
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: naver-sports-monitoring-logs
        path: "sports_exclusive_*.txt"
        retention-days: 7
